version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: merkur_nginx
    environment:
      - NGINX_PORT=8000
    ports:
      - "80:8000"
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/merkur.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - merkur

  client:
    image: merkurorg/merkur-client:latest
    container_name: merkur_client
    command: yarn start
    environment:
      - NEXT_PUBLIC_API_URL=http://165.227.214.134/api
      - NEXT_PUBLIC_SITE_URL=http://165.227.214.134
    depends_on:
        - postgres
    networks:
        - merkur
  dash-admin:
    image: merkurorg/merkur-dashboard:latest
    container_name: merkur_dash
    environment:
      - REACT_APP_API=http://165.227.214.134/api
    depends_on:
        - postgres
    networks:
        - merkur
  server:
    image: merkurorg/merkur-server:latest
    container_name: merkur_server
    command: yarn start
    environment:
        - DB_HOST=postgres
        - DB_USER=postgres
        - DB_PASS=docker
        - DB_NAME=data
    # ports:
    #     - '3333:3333'
    depends_on:
        - postgres
    networks:
        - merkur
  postgres:
    image: bitnami/postgresql:latest
    container_name: merkur_postgres
    environment:
        - POSTGRESQL_PASSWORD=docker
        - POSTGRESQL_DATABASE=data
    # ports:
    #     - 5432:5432
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    networks:
        - merkur

volumes:
    postgres_data:
networks:
  merkur: